# Generated by Django 3.0.5 on 2020-09-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.IntegerField()),
                ('old_name', models.CharField(max_length=50)),
                ('suggested_name', models.CharField(max_length=50)),
                ('food_img', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=50)),
                ('take_nutrient', models.CharField(blank=True, max_length=500)),
                ('avoid_nutrient', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AddField(
            model_name='foodservoire',
            name='deficient_nutrients',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='foodservoire',
            name='food_complement',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='foodservoire',
            name='major_nutrients',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='foodservoire',
            name='major_nutrients_functions',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='calorie',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='calorie',
            name='measurement',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
