# Generated by Django 3.0.5 on 2020-09-08 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_correction_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Correction',
        ),
    ]
